package.json
src/hooks/useRules.ts
src/hooks/useSupportedRegions.ts

Lié a https://github.com/incubateur-ademe/nosgestesclimat/pull/2081.

Ajout d'un script pour lancer le serveur de dev avec le modèle en local

---

package.json
src/app/(layout-with-navigation)/_components/Navigation.tsx
src/app/(layout-with-navigation)/_components/navigation/NavLink.tsx
src/design-system/inputs/Button.tsx
src/design-system/inputs/ButtonLink.tsx
yarn.lock

J'ai ajouté twmerge pour gérer plus simplement les précédences. Je me dis que c'est intéressant pour tous les composant du design system

Refonte / Augmenter la police du menu (et passer l'item actif en gras) (issue 1362)

---

src/app/(layout-with-navigation)/(simulation)/amis/_helpers/getSimulationResults.ts
src/app/(layout-with-navigation)/(simulation)/amis/resultats/_components/VotreEmpreinte.tsx
src/app/(layout-with-navigation)/(simulation)/amis/resultats/_hooks/useGetGroupAndUserFootprints.ts
src/app/(layout-with-navigation)/(simulation)/fin/_components/totalVsTarget/total/Category.tsx
src/app/(layout-with-navigation)/(simulation)/simulateur/[root]/_components/simulateur/charts/BarChart.tsx
src/app/(layout-with-navigation)/(simulation)/simulateur/[root]/_components/simulateur/charts/barChart/Category.tsx
src/app/(layout-with-navigation)/(simulation)/simulateur/[root]/_components/simulateur/charts/inlineChart/SubcategoriesChart.tsx
src/app/(layout-with-navigation)/(simulation)/simulateur/[root]/_components/simulateur/charts/inlineChart/categoriesChart/Category.tsx
src/app/_components/Providers.tsx
src/app/_components/providers/QueryParamsProvider.tsx
src/components/misc/Subcategory.tsx
src/helpers/publicodes/getRuleSumNodes.ts
src/helpers/url/formatResultToDetailParam.ts
src/hooks/useDataServer.ts
src/publicodes-state/simulationProvider/useCategories.ts
src/types/groups.ts

Pour aller avec https://github.com/incubateur-ademe/nosgestesclimat/issues/2048 et https://github.com/incubateur-ademe/nosgestesclimat/issues/2047
(c'est satisfaisant de ouf)

Suppression de "transport . empreinte" et "logement . impact"

---

package.json
yarn.lock

Corrige les warnings des unités dans la doc

Nouvelle version de Publicodes

---

next.config.js
src/app/layout.tsx

…carbone` (#132)"
This reverts commit f44a3a5ac3f26225fced5b68a67eb5ef80608e55.

Revert hotfix 

---

.github/workflows/e2e.yaml
cypress/helpers/simulation/recursivelyFillSimulation.js

Tout est dans le titre ; je passe aussi le temps d'attente au niveau du script de test sur le simulateur (entre chaque question pour laisser le chargement se faire) à 500ms dans le but d'accélérer la complétion des tests

Désactive les tests e2e de personas hors preprod et prod

---

src/app/documentation/_components/DocumentationLanding.tsx
src/app/documentation/_components/DocumentationLandingCard.tsx

Encore temps de faire cette PR pour la release ? 🙏🏼

Release-1-1-2 /`résumé` dans le site (NGC-195)

---

src/constants/dottedNamesMigration.ts
src/publicodes-state/helpers/safeGetSituation.ts
src/publicodes-state/providers/userProvider/filterLocalStorage.tsx

PR liée côté modèle: https://github.com/incubateur-ademe/nosgestesclimat/pull/2270

[Hotfix] fix migration errors

---

src/publicodes-state/helpers/safeGetSituation.ts

fix: new regex to replace only first and last quote

---

src/app/(layout-with-navigation)/(simulation)/fin/page.tsx

Corrige erreur de débutant [NGC-599]

---

src/hooks/navigation/useSimulateurPage.ts
src/hooks/simulation/useSaveSimulation.ts
src/publicodes-state/hooks/useUser/useSimulations.ts

Lié à https://mattermost.incubateur.net/betagouv/pl/zcsuidr6b78edfqd3ctu5cojay

fix: stop overwriting situation when saving it

---

src/app/_components/heading/Buttons.tsx
src/components/form/question/Suggestions.tsx
src/components/questions/Avion.tsx
src/components/questions/Voiture.tsx
src/design-system/inputs/Button.tsx

J'ai aussi modifié le style des boutons des aides à la saisie. Ça me semble moins brouillon (sinon on a beaucoup de boutons sur la page)

Buttons size

---

src/components/form/question/Label.tsx

Pour pouvoir faire un peu de mise en forme :

feat: consider question as md

---

src/components/form/question/NumberInput.tsx
src/components/form/question/mosaic/mosaicQuestion/MosaicNumberInput.tsx

Si quelqu'un a un iPhone pour tester, ce serait chouette

Version mobile : Pavé numérique iOS [NGC-997]

---

src/app/globals.css
src/components/layout/header/headerDesktop/PRIndicator.tsx
src/locales/ui/ui-en.yaml
src/locales/ui/ui-es.yaml
src/locales/ui/ui-fr.yaml

Je voulais corriger le bug sur le `PR=` ici mais la PR est bien ridicule finalement car je ne reproduis pas ahah

Petites pétouilles

---

src/app/(simulation)/(large-layout)/organisations/[orgaSlug]/parametres/_components/OrganisationFields.tsx
src/app/(simulation)/(large-layout)/organisations/[orgaSlug]/parametres/_components/PersonalInfoFields.tsx
src/app/(simulation)/(large-layout)/organisations/[orgaSlug]/parametres/page.tsx
src/locales/ui/ui-en.yaml
src/locales/ui/ui-es.yaml
src/locales/ui/ui-fr.yaml

Merge en attente de celui des PR eau et nouveau layout

🐛 Corrections sur la page paramètres d'organisation

---

src/middleware.ts

Je merge directement (commentage de 7 lignes)

:poop: Comment middleware config to reactivate split testing

---

src/app/_components/Heading.tsx

:bug: Add missing space in text

---

.github/workflows/pr-updater.yaml
.github/workflows/upload-translation-status.yaml

Ici le workflow upload-translation-status.yaml déclenche le trigger d'un autre workflow : problème, ce triggering ne déclenche pas le workflow avec le fichier modifié de la PR mais celui sur preprod. Je suis donc obligé de faire un hotfix pour voir mes modifications prendre effet. Je ne vois pas d'autres solutions mais preneur de suggestions.

:bug: Fix failing workflow

---

src/app/(simulation)/(large-layout)/actions/plus/_components/ActionPlusList.tsx

1 ligne modifiée, je merge direct

:bug: Add check to avoid app crash

---

src/constants/urls.ts

:wrench: deploy assets on scaleway

---

config/redirects.js

⚠️ ATTENTION : ne pas merger avant d'avoir supprimé l'ancien blog et modifié les URLs du nouveau

🔧 Add redirections from old blog to new one

---

src/app/(simulation)/(large-layout)/organisations/[orgaSlug]/parametres/_components/OrganisationFields.tsx
src/app/(simulation)/(large-layout)/organisations/connexion/_components/EmailSection.tsx
src/app/(simulation)/(large-layout)/organisations/connexion/_components/emailSection/VerificationForm.tsx
src/app/(simulation)/(large-layout)/organisations/creer/_components/CreationForm.tsx
src/constants/organisations/organisationTypes.ts
src/hooks/organisations/useCreateOrganisation.ts
src/locales/ui/ui-en.yaml
src/locales/ui/ui-es.yaml
src/locales/ui/ui-fr.yaml
src/types/organisations.d.ts

Ici je rend le champ type d'orga required ; j'en profite pour améliorer le parcours de création de compte en évitant un ré-affichage intempestif du formulaire email après avoir validé son code de vérification.

♻️ Make organisation type field required

---

src/app/(simulation)/(large-layout)/organisations/[orgaSlug]/campagnes/[pollSlug]/_components/AdminSection.tsx
src/types/organisations.d.ts

This reverts commit bd77eb768c75e184ebf93f68a597d9892a7149bf.

Revert "🐛 Hotfix : display back poll admin section when user is administrator (#853)

---

src/locales/ui/ui-en.yaml

Merging directly as one translation is modified

:bug: Wrong translation

---

package.json
src/app/[locale]/(simulation)/(large-layout)/organisations/[orgaSlug]/_components/OurTools.tsx

1 line modified, merging directly

♻️ Update link
